app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    resource: "AppBundle\Controller\UserRESTController"
    prefix:   /api
    type:     rest

shifts:
    resource: "AppBundle\Controller\ShiftRESTController"
    prefix:   /api
    type:     rest

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

linkedin_login:
    path: /login/check-linkedin
