# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        oauth.user_provider:
            id: hwi_auth.oauth_user_provider

    firewalls:
        connect:
            pattern:  ^/connect
            anonymous: ~
        login:
            pattern:  ^/login/?$
            anonymous: ~
        secured_area:
            pattern:  ^/
            anonymous: false
            oauth:
                #provider: fos_userbundle
                resource_owners:
                    linkedin: "/linkedin/login/check"
                login_path: /api
                failure_path: /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider

        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

#        secured_area:
#            pattern:    ^/login
#            anonymous: ~
#            oauth:
#                resource_owners:
#                    linkedin: "/check-linkedin"
#                login_path:        /login
#                failure_path:      /connect
#
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider
#
#           anonymous: ~
#            oauth:
#                resource_owners:
#                    linkedin: "/login/check-linkedin" 
#                   
#                login_path:        /login
#                failure_path:      /login
#
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider
                    #service: my.oauth_aware.user_provider.service
                    #service: linkedin.oauth_user_provider

#        access_control:
#            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
