FROM nodesource/node:4.0

MAINTAINER Matthew Brichacek <mmbrich@gmail.com>

VOLUME /var/www/laravel
WORKDIR /var/www/laravel

#RUN npm update
#RUN npm install npm -g
#RUN npm install express mysql redis -g

CMD ["node", "server.js"]

EXPOSE 3000
